// IMMUNE-NET: Cyber-Biological Node Definitions, Attack Signatures, and States

export const NODE_STATUS = {
  HEALTHY: 'healthy',          // Calm homeostasis, T-cell surveillance active
  INFECTED: 'infected',        // Pathogen detected, anomaly threshold exceeded
  QUARANTINED: 'quarantined',  // Local inflammatory isolation, ingress/egress cut
  IMMUNE: 'immune',            // Memory B-cell fortified, antibody shield active
};

export const ATTACK_CATALOG = [
  {
    id: 'crypto_ransomware',
    name: 'CryptoLock-X (Ransomware Pathogen)',
    severity: 'CRITICAL',
    vector: 'Process fork + High Entropy Disk Write',
    description: 'Autonomous encryptor seeking unmounted volumes. Rapidly alters filesystem entropy.',
    biomarkers: {
      entropySpike: '+94%',
      processForkRate: '480/sec',
      socketEgress: 'Normal',
      syscallDrift: '+76% (SYS_WRITE/SYS_LINK)',
    },
    anomalyScore: 98.4,
    antibodySignature: 'AB-CRYPTO-eBPF-49A1',
    eBpfRule: 'SEC("tp/sched/fork") if p->entropy > 0.82 && disk_writes > 10MB/s => KILL_SIG9',
  },
  {
    id: 'syn_cytokine_flood',
    name: 'SynFlood-Cytokine (DDoS Swarm)',
    severity: 'HIGH',
    vector: 'Raw Socket Half-Open Flood',
    description: 'Massive SYN blast designed to trigger connection table exhaustion and paralysis.',
    biomarkers: {
      entropySpike: '+22%',
      processForkRate: 'Normal',
      socketEgress: '+890% SYN-RCVD',
      syscallDrift: '+88% (SYS_SOCKET/SYS_CONNECT)',
    },
    anomalyScore: 94.7,
    antibodySignature: 'AB-SYN-XDP-77B3',
    eBpfRule: 'SEC("xdp/ingress") if tcp_flags & SYN && rate_limit(ip) > 1000/s => XDP_DROP',
  },
  {
    id: 'exfil_parasite',
    name: 'ExfilParasite-Zero (Stealth Exfiltration)',
    severity: 'HIGH',
    vector: 'DNS Tunneling & Base64 Payload Siphon',
    description: 'Sub-audible exfiltration chunking corporate secrets inside TXT record queries.',
    biomarkers: {
      entropySpike: '+67%',
      processForkRate: 'Low',
      socketEgress: '+410% Port 53 UDP payload',
      syscallDrift: '+54% (SYS_SENDTO)',
    },
    anomalyScore: 91.2,
    antibodySignature: 'AB-EXFIL-DNS-02C9',
    eBpfRule: 'SEC("sock_ops") if dport == 53 && packet_entropy > 4.6 => FLUSH_CONN',
  },
  {
    id: 'kernel_blight',
    name: 'KernelBlight-9 (Privilege Escalation)',
    severity: 'CRITICAL',
    vector: 'Use-After-Free Ring-0 Kernel Hijack',
    description: 'Rootkit seeking capability escalation via corrupted memory descriptor tables.',
    biomarkers: {
      entropySpike: '+51%',
      processForkRate: '+310% thread spawn',
      socketEgress: 'Stealth root shell daemon',
      syscallDrift: '+99% (SETUID/PTRACE)',
    },
    anomalyScore: 99.1,
    antibodySignature: 'AB-KERNEL-LSM-19D4',
    eBpfRule: 'SEC("lsm/cred_prepare") if cred->uid == 0 && parent != systemd => TRAP_CONTAINER',
  },
];

export const INITIAL_NODES = [
  {
    id: 'node-alpha',
    name: 'Node-α [Cortex Gateway]',
    role: 'API Ingress & Edge Proxy',
    ip: '10.0.1.10',
    status: NODE_STATUS.HEALTHY,
    anomalyScore: 4.2,
    activeThreat: null,
    wbcScouts: 12,
    memoryShields: [],
    biomarkers: {
      cpu: 18,
      memory: 34,
      entropy: 0.12,
      socketLoad: 120,
    },
    x: 18,
    y: 28,
  },
  {
    id: 'node-beta',
    name: 'Node-β [Thymus Auth]',
    role: 'Identity & JWT Minting Cluster',
    ip: '10.0.1.15',
    status: NODE_STATUS.HEALTHY,
    anomalyScore: 6.8,
    activeThreat: null,
    wbcScouts: 16,
    memoryShields: [],
    biomarkers: {
      cpu: 24,
      memory: 42,
      entropy: 0.18,
      socketLoad: 85,
    },
    x: 42,
    y: 18,
  },
  {
    id: 'node-gamma',
    name: 'Node-γ [Medulla Vault]',
    role: 'Encrypted Ledger & Key Store',
    ip: '10.0.1.20',
    status: NODE_STATUS.HEALTHY,
    anomalyScore: 2.1,
    activeThreat: null,
    wbcScouts: 20,
    memoryShields: [],
    biomarkers: {
      cpu: 12,
      memory: 58,
      entropy: 0.08,
      socketLoad: 40,
    },
    x: 72,
    y: 25,
  },
  {
    id: 'node-delta',
    name: 'Node-δ [Artery Pay]',
    role: 'Settlement & Payment Gateway',
    ip: '10.0.1.25',
    status: NODE_STATUS.HEALTHY,
    anomalyScore: 5.5,
    activeThreat: null,
    wbcScouts: 14,
    memoryShields: [],
    biomarkers: {
      cpu: 31,
      memory: 49,
      entropy: 0.15,
      socketLoad: 160,
    },
    x: 85,
    y: 58,
  },
  {
    id: 'node-epsilon',
    name: 'Node-ε [Myelin Worker]',
    role: 'Async Task & ML Pipeline',
    ip: '10.0.1.30',
    status: NODE_STATUS.HEALTHY,
    anomalyScore: 8.9,
    activeThreat: null,
    wbcScouts: 10,
    memoryShields: [],
    biomarkers: {
      cpu: 65,
      memory: 72,
      entropy: 0.22,
      socketLoad: 95,
    },
    x: 62,
    y: 78,
  },
  {
    id: 'node-zeta',
    name: 'Node-ζ [Synapse DNS]',
    role: 'Service Discovery & Routing Mesh',
    ip: '10.0.1.35',
    status: NODE_STATUS.HEALTHY,
    anomalyScore: 3.4,
    activeThreat: null,
    wbcScouts: 12,
    memoryShields: [],
    biomarkers: {
      cpu: 15,
      memory: 28,
      entropy: 0.09,
      socketLoad: 210,
    },
    x: 35,
    y: 72,
  },
  {
    id: 'node-eta',
    name: 'Node-η [Marrow Storage]',
    role: 'Blob Cluster & Immutable Snapshots',
    ip: '10.0.1.40',
    status: NODE_STATUS.HEALTHY,
    anomalyScore: 1.8,
    activeThreat: null,
    wbcScouts: 18,
    memoryShields: [],
    biomarkers: {
      cpu: 20,
      memory: 64,
      entropy: 0.06,
      socketLoad: 50,
    },
    x: 15,
    y: 60,
  },
  {
    id: 'node-theta',
    name: 'Node-θ [Lymph Telemetry]',
    role: 'Swarm Orchestrator & Bio-Bus',
    ip: '10.0.1.50',
    status: NODE_STATUS.HEALTHY,
    anomalyScore: 4.0,
    activeThreat: null,
    wbcScouts: 22,
    memoryShields: [],
    biomarkers: {
      cpu: 28,
      memory: 45,
      entropy: 0.14,
      socketLoad: 310,
    },
    x: 48,
    y: 45,
  },
];

export const NETWORK_LINKS = [
  ['node-alpha', 'node-beta'],
  ['node-alpha', 'node-theta'],
  ['node-alpha', 'node-eta'],
  ['node-beta', 'node-gamma'],
  ['node-beta', 'node-theta'],
  ['node-gamma', 'node-delta'],
  ['node-gamma', 'node-theta'],
  ['node-delta', 'node-epsilon'],
  ['node-epsilon', 'node-zeta'],
  ['node-epsilon', 'node-theta'],
  ['node-zeta', 'node-eta'],
  ['node-zeta', 'node-theta'],
  ['node-eta', 'node-theta'],
];
